DataFileName: example_pedestal.dat
TTreeFileName: data/input/Test.root

NModules: 6

Modules:
  - Name: "C257 - scaler"
    Bits: 64
    Channels: 16
    ActiveChannels: 2
    DataType: unsigned
  - Name: "V560N - scaler"
    Bits: 64
    Channels: 16
    ActiveChannels: 2
    DataType: unsigned
  - Bits: 64
    Channels: 16
    ActiveChannels: 2
    DataType: unsigned
  - Bits: 64
    Channels: 16
    ActiveChannels: 2
    DataType: unsigned
  - Bits: 64
    Channels: 16
    ActiveChannels: 2
    DataType: unsigned
  - Bits: 64
    Channels: 16
    ActiveChannels: 2
    DataType: unsigned
  - Bits: 64
    Channels: 16
    ActiveChannels: 2
    
