#canvas options
canvas:
  name:     'SG_comparison'
  title:    'S_{G} comparison; CHN (a.u.); Counts (a.u.)'
  height:   1500
  width:    1500

legend:
  pos: [0.435, 0.71, 0.85, 0.59]
  font: 42
  fillstyle: 0

inputRootPaths: ['data/output/ADC_TDC_comparison.root', 'data/output/S1SG_peakComparison.root']
inputHistNames: ['ADCproj_3_3', 'SG_with_peakSelection_on_S1']
outputPath: 'data/output/SGcomparisons.pdf'

colors: [863, 797]
fillalphas: [0.5, 0.9]
linewidths: [1, 1]

legCaptions: ['S_{G} signal', 'S_{G} signal: first ADC S_{1} peak selected']